server:
   port: 8100
eureka:
   client:
      serviceURL:
         defaultZone: http://localhost:8761/eureka

          
spring:
   application:
      name: api-gateway-Authentication
   cloud:
      gateway:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200/"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
          - id: favoriteservice
            uri: http://localhost:7072/
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            predicates:
             - Path=/api/v1/favoriteservice/**
          - id: userservice
            uri: http://localhost:7071/
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            predicates:
             - Path=/api/v1/userservice/**
          - id: external-service
            uri: http://localhost:7073/
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            predicates:
             - Path=/api/v1/countries/**